### PR TITLE
The first unfinished version for grouped help

### PR DESCRIPTION
**Pull request by yesw2000**
Tadashi,

I just created a framework for grouped help in prun. Please take a look to check if it fits with the original design. You can continue to add more groups and assign the remaining (>100) options to the proper group.

Shuwei

### CODE REVIEW

**Comment by tmaeno** [comment]
Does this work like

$ prun --help
...
submit:
  --noSubmit ..
  ...
output:
  --inOutDsJson INOUTDSJSON ...
  ...
so that users don't have to specify --helpMoreOn=xyz? In any case, I see that you grouped only several options and thus the proposed change is incomplete. I suggest that you group all options and submit another pull request for the complete change.

**Comment by yesw2000** [comment]
Hi Tadashi,

The idea is to have a brief help on one screen for “prun -h/--help”.

I think that it would be better for you to finish the remaining options because you know better the option function in determining which group the options should go or if a new group is needed.

Best,

--Shuwei


On Nov 4, 2019, at 3:55 PM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this work like

$ prun --help
...
submit:
--noSubmit ..
...
output:
--inOutDsJson INOUTDSJSON ...
...
so that users don't have to specify --helpMoreOn=xyz? In any case, I see that you grouped only several options and thus the proposed change is incomplete. I suggest that you group all options and submit another pull request for the complete change.

**Comment by tmaeno** [comment]
Our policy is that only complete changes should be committed to the master branch. If you just want to start a work and ask someone to finish, that is not very useful for the collaboration. Your changes will be reviewed anyway, so it is OK even if some options are assigned to wrong groups.

**Comment by yesw2000** [comment]
Hi Tadashi,

If you prefer me to finish adding new groups and assignment of options, it is fine though it is not the most efficient and fast way. I may ask your question/advice during the group assignment of prun options.

Best,

--Shuwei


On Nov 4, 2019, at 4:22 PM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


Our policy is that only complete changes should be committed to the master branch. If you just want to start a work and ask someone to finish, that is not very useful for the collaboration. Your changes will be reviewed anyway, so it is OK even if some options are assigned to wrong groups.

**Comment by tmaeno** [comment]
Good. I leave this to you as I don't have time to work on this right now. I suggest that you move the custom parser to another module and do the same on pathena.

**Comment by yesw2000** [comment]
Hi Tadashi,

Thanks for your suggestion. It is a good idea to create one module to be shared by both prun and pathena.

One question on the option --nEventsPerFile. What does “file” here refer to? For input files or output files?

Best,

--Shuwei


On Nov 5, 2019, at 12:42 PM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


Good. I leave this to you as I don't have time to work on this right now. I suggest that you move the custom parser to another module and do the same on pathena.

**Comment by yesw2000** [comment]
Hi Tadashi,

One more question:

why use function parse_known_args(), not parse_args()? Is there any ready to ignore unrecognized options in prun argument?

Best,

--Shuwei



On Nov 6, 2019, at 11:35 AM, Shuwei YE <yesw@bnl.gov<mailto:yesw@bnl.gov>> wrote:

Hi Tadashi,

Thanks for your suggestion. It is a good idea to create one module to be shared by both prun and pathena.

One question on the option --nEventsPerFile. What does “file” here refer to? For input files or output files?

Best,

--Shuwei


On Nov 5, 2019, at 12:42 PM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


Good. I leave this to you as I don't have time to work on this right now. I suggest that you move the custom parser to another module and do the same on pathena.

**Comment by tmaeno** [comment]
> --nEventsPerFile

For input files.

> parse_known_args()

This was added in 1.0.0 where many obsolete options were removed. The idea is to not upset users during the major upgrade even if they still use obsolete options since they are silently ignored.

**Comment by yesw2000** [comment]
Hi Tadashi,

Following your suggestion, I created a module pandatools/Group_argparse.py and grouped all prun options.

In addition, I added a feature to print warning message for the deprecated options, but will print error message for other unrecognized options.

Best,

--Shuwei


On Nov 7, 2019, at 1:55 AM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


--nEventsPerFile

For input files.

parse_known_args()

This was added in 1.0.0 where many obsolete options were removed. The idea is to not upset users during the major upgrade even if they still use obsolete options since they are silently ignored.

**Comment by tmaeno** [comment]
Looks good.

**Comment by yesw2000** [comment]
Hi Tadashi,

Is my change ready to be merged into the maser branch? Or need I still make some further tuning? I hope that the pull request can be completed and closed soon.

Best,
Shuwei

**Comment by tmaeno** [comment]
I was waiting that you add the same changes to pathena as suggested before

>  I suggest that you move the custom parser to another module and do the same on pathena.

**Comment by yesw2000** [comment]
Hi Tadashi,

Sorry. I misunderstood your intention.

Anyway, I made similar changes to pathena.

$ scripts/pathena -h
usage: pathena [options] <jobOption1.py> [<jobOption2.py> [...]]

pathena --help' prints a summary of the options

  HowTo is available at https://twiki.cern.ch/twiki/bin/view/PanDA/PandaAthena

optional arguments:
  -h, --help            show this help message and exit
  --helpGroup {PRINT,PATHENA,CONFIG,INPUT,OUTPUT,JOB,BUILD,SUBMIT,EVTFILTER,EXPERT,ALL}
                        Print individual group help (the group name is not
                        case-sensitive), where "ALL" will print all groups
                        together. Some options such as --inOutDsJson may SPAN
                        several groups

Put a few most common examples here
  pathena example-1
  pathena example-2
  pathena example-3

Can you help provide a few typical and most-used examples?

Best,

--Shuwei


On Dec 3, 2019, at 9:38 AM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


I was waiting that you add the same changes to pathena as suggested before

I suggest that you move the custom parser to another module and do the same on pathena.

**Comment by tmaeno** [comment]
E.g.

pathena --inDS ... --outDS ... jobO_1.py jobO_2.py 
pathena --inDS ... --outDS ... --trf "Reco_tf.py --inputAODFile %IN --outputDAODFile %OUT.pool.root ..."
pathena --inOutDsJson inout.json --trf "..."

BTW, the main code of prun has moved to https://github.com/PanDAWMS/panda-client/blob/master/pandatools/PrunScript.py so your arg stuff also has to move from https://github.com/PanDAWMS/panda-client/blob/1e279f22f6e9b0ad39bc88dd9e2a567455178237/scripts/prun .

**Comment by yesw2000** [comment]
Hi Tadashi,

I have added the 3 examples into pandatools//PathenaScript.py.

In addition, I have also moved my changes to pandatools//{PrunScript,PathenaScript}.py.

I have committed all changes into the branch “groupHelp”.

https://github.com/yesw2000/panda-client/tree/groupHelp

Best,

--Shuwei


On Dec 20, 2019, at 6:04 PM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


E.g.

pathena --inDS ... --outDS ... jobO_1.py jobO_2.py
pathena --inDS ... --outDS ... --trf "Reco_tf.py --inputAODFile %IN --outputDAODFile %OUT.pool.root ..."
pathena --inOutDsJson inout.json --trf "..."

BTW, the main code of prun has moved to https://github.com/PanDAWMS/panda-client/blob/master/pandatools/PrunScript.py so your arg stuff also has to move from https://github.com/PanDAWMS/panda-client/blob/1e279f22f6e9b0ad39bc88dd9e2a567455178237/scripts/prun .

**Comment by tmaeno** [comment]
OK, but if you scroll down in https://github.com/PanDAWMS/panda-client/pull/11 you can see "This branch has conflicts that must be resolved". Can you resolve them?

**Comment by yesw2000** [comment]
Hi Tadashi,

I just use all my changes to resolve the conflicts.

Best,

--Shuwei


On Dec 23, 2019, at 5:56 PM, Tadashi Maeno <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, but if you scroll down in #11<https://github.com/PanDAWMS/panda-client/pull/11> you can see "This branch has conflicts that must be resolved". Can you resolve them?

**Comment by tmaeno** [comment]
Thanks!

**Pull request merged**
